name: 2048 to EC2
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            git clone https://github.com/omkarsingad/GA-2048.git
            sudo cp -r GA-2048/* /usr/share/nginx/html/
            sudo systemctl restart nginx
  failover:
    runs-on: self-hosted
    needs: deploy
    if: failure()
    steps:
      - name: failover
        run: |
          ssh ubuntu@${{IPADDR}}
          whoami
          git clone https://github.com/omkarsingad/GA-2048.git
          sudo cp -r GA-2048/* /usr/share/nginx/html/
          sudo systemctl restart nginx
