name: 2048 to EC2
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: linuxagent
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo apt-get update -y
            sudo apt-get install nginx -y
            sudo systemctl start nginx
            sudo systemctl enable nginx
            git clone https://github.com/omkarsingad/GA-2048.git
            sudo cp -r GA-2048/* /usr/share/nginx/html/
            sudo systemctl restart nginx
  failover:
    runs-on: linuxagent
    needs: deploy
    if: failure()
    steps:
      - name: failover
        run: |
          ssh ubuntu@13.201.133.7
          sudo apt-get update -y
          sudo apt-get install nginx -y
          sudo systemctl start nginx
          sudo systemctl enable nginx
          git clone https://github.com/omkarsingad/GA-2048.git
          sudo cp -r GA-2048/* /usr/share/nginx/html/
          sudo systemctl restart nginx